# ~/.streamlit/config.toml

[theme]
primaryColor = "#669673"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#272b29"
textColor = "#FAFAFA"
font = "sans serif"

[theme.light]
primaryColor="#669673"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#e9f2eb"
font = "sans serif"
textColor = "#262730"